Plugin cleanup
jellyfin/jellyfin-plugin-anime pull request #6
Opened 2019-01-24 12:05 UTC by Matt07211

This is general cleanup, that is removing unneeded files (aka files that have been fully commented out) as well as removing the German specific language option (would rather let translations handle anything like this). Also choose to drop Anisearch and Proxer in favor of maintaining just the big 3 (AniDB, Anilist and MAL). And in all honest, I haven't heard of those two outside of the plugin, if you have a good and appropriate reason to add them back in please voice your concerns.

With this out of the way, time to fix up the plugins bugs and add some more features to it.

2019-01-24 21:31 UTC, Bond-009 requested changes
Don't know why, but you are deleting files that weren't commented out.

2019-01-24 21:31 UTC, Bond-009 commented on MediaBrowser.Plugins.Anime/Configuration/PluginConfiguration.cs
> +	public int AniDB_wait_time { get; set; }
Weird indentation

2019-01-24 21:31 UTC, Bond-009 commented on MediaBrowser.Plugins.Anime/anime-lists-net/AnimelistAnime.cs
> -        public string AniSearchId { get; set; }
Why remove these?

2019-01-24 21:31 UTC, Bond-009 commented on MediaBrowser.Plugins.Anime/Providers/Proxer/ProxerSeriesProvider.cs
> -    public class ProxerSeriesProvider : IRemoteMetadataProvider<Series, SeriesInfo>, IHasOrder
Why delete this file?

2019-01-24 22:00 UTC, Matt07211 commented
Re: Discussed files above, I was in favour of just maintaining the big 3 metadata and list provider's, but others would rather keep them in at this time, I'll revert those changes and add them back in tonight

2019-01-25 05:54 UTC, Matt07211 commented on MediaBrowser.Plugins.Anime/Configuration/PluginConfiguration.cs
> +	public int AniDB_wait_time { get; set; }
Fixed

2019-01-25 05:55 UTC, Matt07211 commented on MediaBrowser.Plugins.Anime/Providers/Proxer/ProxerSeriesProvider.cs
> -    public class ProxerSeriesProvider : IRemoteMetadataProvider<Series, SeriesInfo>, IHasOrder
Reverted change.

2019-01-25 05:55 UTC, Matt07211 commented on MediaBrowser.Plugins.Anime/anime-lists-net/AnimelistAnime.cs
> -        public string AniSearchId { get; set; }
Reverted change.

2019-01-25 05:57 UTC, Matt07211 commented
As per discussion in the matrix I have reverted the changes that removed 2 metadata providers, so all this pull request should now be doing is removing completely useless and unused code.

2019-01-25 06:20 UTC, hawken93 commented
LGTM :)

2019-01-26 13:15 UTC, Bond-009 approved these changes

2019-01-26 13:16 UTC, merged