Various Anilist improvements
jellyfin/jellyfin-plugin-anime pull request #70
Opened 2020-05-17 21:00 UTC by Musi13

2020-05-17 21:18 UTC, Musi13 commented
Closed and reopened because I hit create before I was done editing 😅

2020-05-17 21:21 UTC, Musi13 commented on Jellyfin.Plugin.Anime/Providers/AniList/AniListApi.cs
> +    /// 🛈 THIS IS AN UNOFFICAL API INTERFACE FOR JELLYFIN
Summary of changes in this file:
* Fixed indentation (mostly in graphql)
* Moved some functions to be methods of the Media object
* Update comments

2020-05-17 21:22 UTC, Musi13 commented on Jellyfin.Plugin.Anime/Providers/AniList/AniListMovieProvider.cs
> +using System;
This file is basically a copy of SeriesProvider with `sed s/Series/Movie/`

2020-05-17 21:28 UTC, Musi13 commented on Jellyfin.Plugin.Anime/Providers/AniList/ApiModel.cs
>  ﻿using System;
Most of this file is serialization setup for the JSON parser, attributes come from the [AniList API Docs](https://anilist.gitbook.io/anilist-apiv2-docs/) and mostly the [API v2 GraphQL Docs](https://anilist.github.io/ApiV2-GraphQL-Docs/). There's also methods added to convert values from AniList's representation to Jellyfin's.

The idea is you use Media/MediaSearchResult internally (to the plugin) and convert it to the relevant Jellyfin object type through ToMovie and ToSeries, that way both providers can share most of the code.

2020-07-19 20:11 UTC, crobibero approved these changes

2020-07-19 20:20 UTC, Bond-009 requested changes
Missing braces

2020-07-19 20:20 UTC, Bond-009 commented on Jellyfin.Plugin.Anime/Providers/AniList/AniListApi.cs
> +                return media;
Braces everywhere

2020-07-19 20:20 UTC, Bond-009 commented on Jellyfin.Plugin.Anime/Providers/AniList/AniListApi.cs
> +            return (await WebRequestAPI(AnimeLink.Replace("{0}",id))).data?.Media;
```suggestion
            return (await WebRequestAPI(AnimeLink.Replace("{0}", id))).data?.Media;
```

2020-07-19 21:26 UTC, oddstr13 approved these changes

2020-07-19 21:31 UTC, merged